@startuml


package block {
    class Blocks {
        + pushMarkdown(string): self
        + toHtml(): string
    }

    abstract class Block {
        + toHtml(): string
    }

    Blocks -r-> "*" Block

    abstract class SingleLineBlock {
    }

    abstract class MultiLineBlock {
        + pushLine(string): self
    }

    SingleLineBlock -u-|> Block
    MultiLineBlock -u-|> Block

    Paragraph -u-|> SingleLineBlock
    Quote -u-|> SingleLineBlock

    OrderedList -u-|> MultiLineBlock
    UnorderedList -u-|> MultiLineBlock
    CodeBlock -u-|> MultiLineBlock
}

package line {
    class Line {
        + pushChar(char): Line
        + toHtml(): string
    }

    interface Text {
        + pushChar(char)
        + toHtml(): string
    }

    Line -r-> "*" Text

    Prime -u-|> Text
    Strong -u-|> Text
    Emphasis -u-|> Text
    Strikethrough -u-|> Text
    Code -u-|> Text
    Anchor -u-|> Text
    Break -u-|> Text
    Mention -u-|> Text
}

block -d-> "*" Line

@enduml